name: Release Node.js app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish image to Docker Hub
    steps:
    # Checkout to the repository
    - uses: actions/checkout@v4
    
    # We need to login so we can later push the image without issues.
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
        
    # Builds youngpickling/rimuok-frontend:latest
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: youngpickling/rimuok-frontend:latest
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    name: Deploy to render.com
    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'main'
        env:
          deploy_url: ${{ secrets.DEPLOY_HOOK }}
        run: |
          curl "$deploy_url"